name: "Latest tag from master branch"
env:
  DOCKERHUB_REPOSITORY: ghcr.io/elecena/socks5-server:latest
  PROXY_USER: foobar
  PROXY_PASSWORD: s3cr3t

on:
  pull_request:
    branches: master
  push:
    branches: master
  release:
    types: [published, edited]

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: hadolint
      uses: hadolint/hadolint-action@v3.3.0
      with:
        ignore: DL3018
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: elecena/socks5-server
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
      -
        name: Run docker build
        run: docker build --tag ${DOCKERHUB_REPOSITORY} .
      -
        name: Show docker images
        run: docker images
      -
        name: Start and use the container
        run: |
          set -x
          docker run -d --name socks5 ${DOCKERHUB_REPOSITORY}
          sleep 3
          docker ps
          curl --ipv4 --proxy socks5://${PROXY_USER}:${PROXY_PASSWORD}@0.0.0.0:1080 -vI -H "user-agent: socks5/healthcheck" http://example.com/
      -
        name: Print logs
        if: always()
        run: docker logs socks5
