name: "Latest tag from master branch"
env:
  DOCKERHUB_REPOSITORY: ghcr.io/elecena/socks5-server:latest

on:
  pull_request:
    branches: master
  push:
    branches: master
  release:
    types: [published, edited]

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: hadolint
      uses: hadolint/hadolint-action@v3.3.0
      with:
        ignore: DL3018
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v6
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3.3.1
      -
        name: Print builder available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: elecena/socks5-server
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'master') }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{raw}}
      -
        name: Run docker build
        run: docker build --tag ${DOCKERHUB_REPOSITORY} .
      -
        name: Show docker images
        run: docker images
